### ISSUE TITLE
extension doesn't work at all

### ISSUE THREAD

**Issue by RieGo** [kurtextrem/Improved-for-Instagram#1]
tried to use the extension as guest and logged in. in both cases no change to the default instagram page.
maybe it's realted to this error in console: 

> i.instagram.com/api/v1/feed/user/389443387/reel_media/ Failed to load resource: the server responded with a status of 400 ()

maybe it only works on the homepage? not on user pages.

**Comment by kurtextrem** [comment]
Thank you for the report.

This extension does not modify user pages, as those seem fine on desktops. Which version of Chrome are you using (see chrome://version)?

After logging in, please refresh the page (F5) and take a look if it's working afterwards. I've tested in a new user profile and it's working for me.

**Comment by RieGo** [comment]
alright. then i apologize. i just checked: on the instagram homepage it works. :)
so feel free to close this issue.

**Comment by kurtextrem** [comment]
No worries :)
Do you have any ideas for the profile page? What would you improve?

**Comment by RieGo** [comment]
to be honest i really new to instagram on desktop. so i guess i'm not much of an help in that matter, but i might have found a problem:

![image](https://cloud.githubusercontent.com/assets/363418/22751807/434d0bf2-ee36-11e6-82e1-823c31a2ce3e.png)

in the screenshots it looks like there should be several columns.
on my pc it's just a single column.
using Chrome 57.0.2987.21 beta on a 21:9 2K display

**Comment by RieGo** [comment]
alright, i have no idea what just happened, but i opened the page again and now it works.

**Comment by kurtextrem** [comment]
It seems like Instagram did a change - currently investigating.

**Comment by kurtextrem** [comment]
A lot of time has passed. If it still not working, let me know.
