### ISSUE TITLE
"Unexpected token ..."

### ISSUE THREAD

**Issue by KLVN** [kurtextrem/Improved-for-Instagram#13]
The 3 column layout is working, although sometimes images aren't loaded and stay gray, but clicking on the 3 dots does nothing.

```
InstagramAPI.js:23 Uncaught SyntaxError: Unexpected token ...

main.js:106 Uncaught TypeError: window.getInstagram is not a constructor
    at main.js:106
    at main.js:173
```

After clicking on the dots:
```
main.js:135 Uncaught TypeError: Cannot read property 'liked' of undefined
    at HTMLAnchorElement.a.onclick (main.js:135)

```

**Comment by kurtextrem** [comment]
Thank you for the report, will look into it as soon as possible!

**Comment by kurtextrem** [comment]
Regarding the gray images: I'm not sure if I can change that, that should be because of how Instagram loads next images.

**Comment by kurtextrem** [comment]
New version just published, let me know if the 3 dots are working now (wait 30min / few hours until the update rolled out).

**Comment by KLVN** [comment]
Ayyy, that was fast 🔥🔥🔥. Thanks, it's working now.
