### ISSUE TITLE
Open image bigger.

### ISSUE THREAD

**Issue by d0null** [kurtextrem/Improved-for-Instagram#14]
It will be awesome that if you hover a photo you could press a thing and show that image way bigger.

**Comment by kurtextrem** [comment]
This is possible with right clicking the image and then "open in new tab" :)

Am 12.06.2017 10:48 nachm. schrieb "Daniel" <notifications@github.com>:

**Comment by KLVN** [comment]
> press a thing

or right-click on the image and then press "D".
