### ISSUE TITLE
Not working in conjunction with "Chrome IG Story"

### ISSUE THREAD

**Issue by dematch1** [kurtextrem/Improved-for-Instagram#15]
Chrome IG Story is (rightfully) being recommended to use it along with this one according to the chrome store description. Unfortunately they don't work together. My instagram looks like this:
![insta1](https://user-images.githubusercontent.com/28808365/27155146-13718e00-5158-11e7-999b-7218011c350a.jpg)
I can see my stories but my normal feed is gone, you can only see the loading icon running and running without anything happening.
Also I'm getting the follow error (in German, tell me if you need a translation) at chrome://extensions/
![insta2](https://user-images.githubusercontent.com/28808365/27155205-5afd430e-5158-11e7-83f2-df2b55baa874.jpg)

**Comment by kurtextrem** [comment]
Seems weird. I get the same warning and have the same setup. It might be that Instagram is testing something and not everything is compatible. 
Could you please right click anywhere, then "Untersuchen" and tell me if there are any errors in the console?

**Comment by kurtextrem** [comment]
Interesting, your Chrome IG Story extension is really outdated. The latest version is 2.0.2. Can you try the following steps?
1. Go to chrome://extensions/
2. Check "Entwicklermodus"
3. Click "Erweiterungen jetzt aktualisieren"

If that doesn't work you could try to reinstall Chrome IG Story from the webstore.

**Comment by dematch1** [comment]
Oh well, the outdated Chrome IG Story was indeed the cause of failure. It never got updated, neither automatically or when done manually, reinstalling helped. Thank you!
