### ISSUE TITLE
Search results behind images

### ISSUE THREAD

**Issue by KLVN** [kurtextrem/Improved-for-Instagram#16]
Hey,
search results are displayed behind the images.

![insta_extension](https://user-images.githubusercontent.com/8047980/27323620-71404532-55a2-11e7-9dce-9c61414d7172.PNG)

Version: 2.2.2
Chrome: Version 58.0.3029.110 (64-bit)

Thanks :)

**Comment by kurtextrem** [comment]
Thank you Kelvin, I've fixed this. ETA 30min.

**Comment by KLVN** [comment]
It's now on top, but this little arrow is missing a box shadow.
![insta_extension2](https://user-images.githubusercontent.com/8047980/27339868-3f8cb430-55d9-11e7-83b2-9a278b3706c1.PNG)

Easy (and ugly) fix would be
```css
._pnw2j {
    ...
    -webkit-box-shadow: 0 0 5px 1px rgba(0,0,0,.0975)!important;
    ...
```
:D

Thanks

**Comment by kurtextrem** [comment]
Thanks again, fixed that (I did not add `box-shadow` as its performance implications are relatively high; A bigger border almost looks the same and works in this case)
