### ISSUE TITLE
Tags not showing

### ISSUE THREAD

**Issue by KLVN** [kurtextrem/Improved-for-Instagram#17]
Tags are not shown, when clicking on an image, e.g. [this post](https://www.instagram.com/p/BW3W3BJlc3X/).

... well, they are shown, but the `z-index` is messed up :D

---

Location of problem:
Selector:
`#react-root > section > main > div > div > article > div._h5v2a._kqf30 > div > div > span:nth-child(2)`

XPath:
`//*[@id="react-root"]/section/main/div/div/article/div[1]/div/div/span[1]`

**Comment by kurtextrem** [comment]
Damn, seems like IG has changed something in their DOM again.

I'll update tomorrow morning (it's 22:05 in Germany). Thank you for the report Kelvin!

**Comment by kurtextrem** [comment]
Fixed and published :)

**Comment by KLVN** [comment]
Thanks 👍
(I'm from Germany, too ;) )

**Comment by KLVN** [comment]
Moin, tags are again not shown.

Version: 2.2.12

**Comment by kurtextrem** [comment]
Servus, danke noch mal :D
