### ISSUE TITLE
Add black theme

### ISSUE THREAD

**Issue by kurtextrem** [kurtextrem/Improved-for-Instagram#18]
A contrast theme for the night so to say.

(User suggested)

**Comment by KLVN** [comment]
How do you want to implement other CSS styles? Combined in one file with names like `nav`, `nav-night`, `like`, `like-night`, ... or a separate `content-night.css` file that is loaded if the black theme is enabled or maybe a certain time passed? (_if later than 21:00, then use `content-night.css`_)

**Comment by kurtextrem** [comment]
The latter one I guess.

**Comment by KLVN** [comment]
I'm trying to design one, https://github.com/KLVN/Improved-for-Instagram/issues/1

**Comment by kurtextrem** [comment]
I have another idea, we have one main stylesheet that is injected at all times and `content-night.css` that is only injected at night time.
Another good idea would be to add an option to disable/enable + from when (hour) to when it is enabled

If you need any help (building the extension for example) let me know (I'll add the new injection mechanism asap)!

**Comment by KLVN** [comment]
Ich schreib' mal wieder auf Deutsch, ist entspannter :D

Wird `night.css` (oder `content-night.css`?) gleich wie `content.css` sein, allerdings weiter ausgebaut mit dem dunklen Design oder soll `night.css` nur die Sachen enthalten, die anders sind und so eine Art Add-on sein?

Habe mit dem Design schon etwas angefangen, fehlen nur noch so Kleinigkeiten wie die Liste in der Searchbar, allerdings weiß ich nicht wie ich diesen einen Commit (https://github.com/KLVN/Improved-for-Instagram/commit/20440e8ac23366757f1645c7ad3e99d6db23099e) aus meinem Repo in deins _pull requeste_, ohne die anderen zwei unwichtigen die ich da noch habe 😅

Ich habe mich auch schon daran versucht diesen Wechsel-Mechanismus zu basteln, war mir aber nicht sicher wie ich es umsetzen sollte. Kann man nachträglich eine CSS-Datei entfernen und damit auch das Design wieder ändern, oder müsste man beim umstellen die Seite erneut laden? [Hier](https://codepen.io/secondfret/pen/DFpwJ) ist zum Beispiel eine CSS-only Methode, um das Design zu ändern, wäre dann aber wieder alles in einer Datei.

Im Moment arbeite ich mit der originalen CRX Datei, die ich entpackt habe und jetzt verändere. Sieht zwar etwas anders aus, als auf GitHub, funktioniert aber zum arbeiten :D

**Comment by kurtextrem** [comment]
Meiner Meinung nach wäre das Sinnvollste ein Basic Sheet zu haben, das die Style Anpassungen hat (also generelles fürs Layout).
Am besten wäre es also dann `night.css` nur mit Farben auszustatten. So bleibt alles immer getrennt, weil im "light" (also standard) mode ändern wir Farben ja nicht.

Beim PR kann man eine Commit Range aussuchen, kannst ja einfach mal einen erstellen - das GitHub interface ist da eigentlich benutzerfreundlich (und man kann PRs jederzeit noch editieren)

Wenn der PR durch ist, kann ich dir auch gern access zum repo hier geben, dann kannst du den night mode immer updaten ohne n PR zu erstellen :D Aber erstmal ists die Erfahrung Wert seinen ersten(?) PR durchzubekommen.

**Comment by KLVN** [comment]
Ok, habe im jetzigen night.css noch das Basic Sheet als Grundgerüst drin. Werde da noch weiter aufräumen.

Habe meinen Fork jetzt einfach nochmal neu gemacht und den PR gestellt. Rechte für die Repo wären zwar cool, möchte hier aber nichts zerschießen, sondern erst noch dazulernen :D

**Comment by kurtextrem** [comment]
Hi @KLVN, wie geht's wie stehts?

Die Options-Seite ist nun soweit fertig und ich würde mich natürlich auf ein Night Theme freuen :)

**Comment by KLVN** [comment]
Moin,

ich muss schauen, ob ich über die Ostertage Zeit finde. Instagram hat wieder einmal vieles geändert, muss also fast bei Null wieder anfangen... 👌🔥

**Comment by KLVN** [comment]
Das Fundament ist gelegt (Main feed, Profil, Popup für Bilder und die eigenständige Seite für Bilder), habe aber neu geforked und dadurch kann ich bei meinem PR #22 nichts mehr anfügen (fettes *gg* an dieser Stelle :D). Das dunkle Theme sollte für die grundlegendsten Aufgaben reichen, um die anderen Dinge kümmere ich mich später oder jemand anderes macht noch paar PR's.

https://github.com/KLVN/Improved-for-Instagram/commit/a6d25b0e74d6173a4892c9fda10c10c7e2302878

**Comment by KLVN** [comment]
> Weißt du, wie du den Night Mode testen kannst?

Habe in der `main.js` ein `injectCSS('night')` eingefügt :D

> Erstell am besten einfach einen neuen PR

Sorry für die Umstände, der Fehler fiel mir dann auch kurz nach dem Löschen auf 😅
#40

**Comment by kurtextrem** [comment]
Ich schließ das hier mal, wir haben ja den offenen PR bzw. die Extension shipped ja momentan schon mit deinem Night Mode :)
