### ISSUE TITLE
The extension doesn't seem to work anymore

### ISSUE THREAD

**Issue by haydenmlh** [kurtextrem/Improved-for-Instagram#2]
No errors logged in console either, not familiar with programming so can't identify the issue.

**Comment by kurtextrem** [comment]
Can't reproduce after clearing cookies and cache. Is there anything that looks different from before? (Something like the navigation, e.g.: http://prntscr.com/essv0d)

**Comment by kurtextrem** [comment]
If it still does not work, let me know.
