### ISSUE TITLE
Unable to install in Chrome for Linux

### ISSUE THREAD

**Issue by dematch1** [kurtextrem/Improved-for-Instagram#21]
I'm getting this error when trying to install the extension in both Chrome and Chromium for Ubuntu/Linux:

![screenshot from 2017-09-19 21-43-56](https://user-images.githubusercontent.com/28808365/30613182-75e50c9e-9d87-11e7-8f82-87632166f770.jpg)

I'm unable to use the extension for some weeks now because of this. I've tried using both (official) Chrome and (open-source) Chromium on _Ubuntu GNOME 17.10_ and _Lubuntu 16.04_ with a fresh profile - no success anywhere. 

Any idea why?

**Comment by kurtextrem** [comment]
Thank you for the report! I've fixed this issue... not sure how I didn't notice and it works locally.
