### ISSUE TITLE
"Package is invalid"

### ISSUE THREAD

**Issue by Sl0b** [kurtextrem/Improved-for-Instagram#3]
Hi,
I could not install your extension, it gave me this:
![error](https://cloud.githubusercontent.com/assets/11925412/25424654/65815150-2a69-11e7-9598-1934226700f4.png)

Is it on my side? I probably forgot something.

**Comment by kurtextrem** [comment]
Thank you so much for the report, it is my bad. Will fix asap.

**Comment by kurtextrem** [comment]
New version is published to the Chrome Web Store. However, it can take up to 60min until it's fixed.
Thank you again for reporting.
