### ISSUE TITLE
Displays results that do NOT relate to the search

### ISSUE THREAD

**Issue by sakura22** [kurtextrem/Improved-for-Instagram#35]
Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Windows 10 Home 64 bit
Opened and logged into instagram.com in Chrome, searched for a tag which displayed 93,000+ posts, clicked the '...' to launch kurtextrem extension and all the results that displayed in instagram/chrome have now been replaced by completely different results.

I've 'cleared' the outdated data, as suggested in your '?' page. Closed the browser and opened it to start the process again and I still get the same results. 

Any idea how to fix this?

**Comment by kurtextrem** [comment]
Hi @sakura22, this is not the way the extension works. The 3-dots page shows your liked and saved posts from your Instagram account.

**Comment by sakura22** [comment]
Thanks for the clarification.  The 'liked and saved stuff' is not what I liked and saved. But that's not what I'm interested in. 

How do I download the videos I want to download?
I've tried clicking the download button but all that appears is the word 'javascript:;'.
I've turned off all extensions except yours.
![image](https://user-images.githubusercontent.com/18496238/33794447-89be3da2-dd20-11e7-9af7-e9e7b18b8fcf.png)

**Comment by kurtextrem** [comment]
What is displayed there? Could you please compare with what the app shows?

The second one is a bug, I'll release an update now :)

**Comment by kurtextrem** [comment]
Do you have any further ideas/questions? :)

**Comment by sakura22** [comment]
Thanks so much for your quick replies. No other problems apart from the inability to download. I'm not too worried about the search results. Have a great night and I'll look forward to your update.

**Comment by sakura22** [comment]
Beautiful extension btw - love it ♥♥!!

**Comment by kurtextrem** [comment]
Thank you for this comment, it is very motivating to hear this 😄
