### ISSUE TITLE
Timeline feed couldn't display in 4 or 6 posts per row

### ISSUE THREAD

**Issue by luckyjacky51** [kurtextrem/Improved-for-Instagram#41]
I try to set it displaying 4 or 6 posts per row in my timeline feed, but it always displaying only 2 posts per row, anyone else has the same issue?

While in my liked or saved view, it displaying as 4 posts per row

**Comment by kurtextrem** [comment]
This is an oversight on my part, sorry. However, I can't provide the option 6 anymore as Instagram doesn't really work with it.
I've published a new version to fix it.

**Comment by kurtextrem** [comment]
You're welcome! If you have any other suggestions or issues, please let them hear me :)
