### ISSUE TITLE
Design contribution proposal

### ISSUE THREAD

**Issue by ihtiht** [kurtextrem/Improved-for-Instagram#42]
Hi,

I am a graphic designer. I contribute to open source projects. I can also contribute to this project.  If you need any design, you can say it without hesitation. I like the idea of ​​the current logo. I can develop it if you want.

**Comment by kurtextrem** [comment]
Sure, I'd take any advices / ideas / contributions!

The thing is, the logo must not look similar to the original Instagram design. That's what it looked like initially: https://github.com/kurtextrem/Improved-for-Instagram/blob/77e7e7731638658e31bacab600ca014762849835/src/img/icon-128.png

**Comment by ihtiht** [comment]
I am sorry for being late. Here are my designs;


![imrovedinstagram](https://user-images.githubusercontent.com/36369736/40864374-3ea11050-65fc-11e8-8189-6a5c317b3b6d.jpg)


If you have something you want to add or change, do not hesitate to say it. For example about color.  

I will be waiting for your feedback ..

**Comment by kurtextrem** [comment]
No worries about the delay!

The icon looks great!!! However, I'm unsure if Instagram allows that icon. Would you say it looks too similar to the Instagram original icon (especially the left version)?

**Comment by ihtiht** [comment]
The necessary information can be found here. https://en.instagram-brand.com/guidelines/general


As far as I understand it will not be a problem.

**Comment by kurtextrem** [comment]
Sounds great, next update I'll include the icon. (Or do you want to make a Pull Request?)

In what way should I mention you? I'd add you to the Readme and the About page - would you like anything specific?

**Comment by ihtiht** [comment]
I will prepare the files and open a PR soon. You can add me as "Ibrahim Tenekeci".

**Comment by ihtiht** [comment]
I sent a PR.  https://github.com/kurtextrem/Improved-for-Instagram/pull/43

 If you have any need, do not hesitate to say it.

**Comment by kurtextrem** [comment]
Really loving the new logo, thanks a loooot!!! 🎊 
I will of course add you to the help/about section on the 3-dots page

**Comment by ihtiht** [comment]
Thanks, I am glad that I contributed. I'm here if you need a design for other projects. Remember me.. 



Mission accomplished 😎

**Comment by kurtextrem** [comment]
Sadly, after two 1/2 years I've now received this:
```
As a responsible brand owner, Instagram must protect consumers from confusion and prevent dilution of its famous marks. Using a name that is similar to or includes “Instagram,” “IG,” “Insta,” or “gram,” and/or logos that look like Instagram’s logos may be confusing to people, or may make it harder for them to distinguish between different apps. Your use INSTAGRAM in the name of your extension, a gradient color that calls to mind Instagram’s Spectrum Multi-color Gradient, and use of an image in your extension’s icon that mimics Instagram’s Camera Logo Glyph Multi-color is harmful to the Instagram brand—particularly when the product and/or service you are offering modifies the Instagram user experience.  We assume you have no interest in being mistaken for Instagram, or creating the mistaken impression that you are affiliated with or endorsed by Instagram. In order to avoid this, we request that you:

·         cease use of INSTAGRAM, including “instagram.com,” in the name of your extension;

·         cease use of an image in your extension’s icon that mimics Instagram’s Camera Logo Glyph Multi-color;

·         cease use of colors that call to mind Instagram’s Spectrum Multi-color Gradient;

·         make corresponding changes to your promotion of the extension on GitHub, Reditt, and elsewhere; and  

·         refrain from using any other Instagram marks in conjunction with this extension, or with any other websites, products, or services you own, sponsor, or otherwise promote.

 

More detailed information about how to communicate your relationship with Instagram and how to correctly use Instagram’s brand assets can be found in Instagram’s Brand Guidelines, available here: https://www.instagram-brand.com. It is important that you develop your own distinctive branding for your extension and service, and use Instagram’s trademarks only as specifically authorized under Instagram’s policies. 
```

Gotta switch back to the previous icon, sadly. :(
