### ISSUE TITLE
Likes and saves simply not showing?

### ISSUE THREAD

**Issue by shawerma** [kurtextrem/Improved-for-Instagram#48]
![screen shot 2018-06-25 at 5 18 23 pm](https://user-images.githubusercontent.com/34974420/41859188-e8a4b168-789b-11e8-8611-336d0266da44.png)

What can I do? it was stuck on old posts for a while until I pressed 'clear' and now I have nothing :(

**Comment by kurtextrem** [comment]
Which browser version are you using? It seems like the JavaScript doesn't execute.

**Comment by shawerma** [comment]
Im on a mac using latest version of chrome (version 67 i believe?)

**Comment by kurtextrem** [comment]
That's really weird then... Could you please right-click on the page and click "Inspect" (last item of that menu) and do a screenshot of the console?
