### ISSUE TITLE
Liked photos page not updating 

### ISSUE THREAD

**Issue by ratherlegit** [kurtextrem/Improved-for-Instagram#49]
Hey, love the extension, it's vastly superior to the standard view. However, a new issue popped up for me about 1-2 weeks ago. The Liked photos page has stopped updating with new liked photos. Not sure what changed, but would love for this to be fixed!

Thank you.

**Comment by kurtextrem** [comment]
Thank you for the report!

Have you tried clearing the data on the 3-dot page on the "?" page?
If this doesn't work:
- please right click anywhere on the 3-dot page and do a screenshot (make sure "Console" is open. If not, click the "Esc" key. Explanation: There are error messages for me to read probably)
- do the same for Instagram.com after opening the 3-dots page from there

Which Chrome version do you have?

**Comment by ratherlegit** [comment]
Hey, something must have changed because it's now working again.

Thank you!
