### ISSUE TITLE
Scrolling is broken

### ISSUE THREAD

**Issue by jerblack** [kurtextrem/Improved-for-Instagram#50]
I am using your extension in Chrome 69.0.3497.92 on Windows 10 on an ultrawide monitor, and I am having problems with scrolling. WIth this extension enabled, when I scroll down several rows, at a certain point it will start jumping back to the previous row as I scroll. For instance, Say it happens as I scroll from the 8th to the 9th row, as I scroll to the point where the 9th row is partially visible, the page jumps back to the 8th row. If I keep scrolling, it keeps jumping back from the 9th row to the 8th row and I can no longer scroll down any further. All of my settings are at their defaults with the exception of night mode being turned on. Any ideas?

**Comment by kurtextrem** [comment]
Hi @jerblack, thank you for the report.
How many posts do you have per row?

**Comment by jerblack** [comment]
4. This was the default for me.

**Comment by kurtextrem** [comment]
I found the bug for the disappearing options, however I still don't know why your scrolling doesn't work.

**Comment by jerblack** [comment]
Ok, after further testing this was a false alarm. I just noticed the scrolling problem at the same time I started using this extension, but now I get the jumping without your extension enabled, so it's probably one of my other extensions. I'll continue troubleshooting, but I don't think this was your fault. Thanks.

**Comment by kurtextrem** [comment]
Thank you for the report anyway!
