### ISSUE TITLE
Used to be able to select 3 posts per row. Now I can only select 2 or 4

### ISSUE THREAD

**Issue by afonsocarmo** [kurtextrem/Improved-for-Instagram#51]

**Comment by kurtextrem** [comment]
Was 3 per row working for you correctly?

**Comment by afonsocarmo** [comment]
Yeah I had no problem with it, it was perfect for me because my 13" screen is too small horizontally for 4 per row and too small vertically for 2

**Comment by kurtextrem** [comment]
Interesting, originally I did not intend to allow anything else than 2 or 4, because Instagram didn't work correctly if set to an uneven amount or greater than 4.
I will bring the option back.

**Comment by afonsocarmo** [comment]
Wow I really appreciate it dude

**Comment by kurtextrem** [comment]
I really wonder why it's working correctly for you. When I try scrolling with 3 posts per row, the scrolling is buggy.

**Comment by kurtextrem** [comment]
Fixed it, will release it tomorrow morning or later today.

**Comment by afonsocarmo** [comment]
I really had no problem with it when I used it
