### ISSUE TITLE
Likes have a gap between 24h and 6 months

### ISSUE THREAD

**Issue by Nethya** [kurtextrem/Improved-for-Instagram#55]
Hello, seeing all Likes on PC only shows those within last 24h, and from 6+ month. There seems to be a gap between anything older than one day, and last six months. On phone they are shown normally.

**Comment by kurtextrem** [comment]
Hi, sorry for the late reply, I'm busy with exams at the moment.

I can't really reproduce this problem. The timestamps next to posts are the timestamps when the post was made, not liked. Could this be the issue?
