### ISSUE TITLE
Can't scroll past certain points, scrolling keeps jumping backwards in feed.

### ISSUE THREAD

**Issue by bluehairisnice** [kurtextrem/Improved-for-Instagram#64]
I'm currently set to view two posts per row. It has been working fine for quite a while. 

In the last few weeks: Scrolling through my feed works as per normal for a bunch of rows, then suddenly gets stuck. Scrolling down with the mouse results in the feed jumping back a row. It will keep doing it repeatedly - I can't scroll past that jumping row.  Sometimes I can get past the sticking point by dragging the scroll bar down. But scrolling will just get stuck again a few more rows down. 

This doesn't happen when viewing a single account, scrolling through hashtagged posts, or when viewing one picture per row in my feed. It only seems to happen when viewing 2, 3, 4 pics perfeed  row.

**Comment by kurtextrem** [comment]
Weird, doesn't happen for me. It could be that Instagram is running an experiment and I'm not in the experimental group.

**Comment by vwsvws** [comment]
Same issue on my end. I'm set to view 4 posts per row. If I scroll down slowly, the feed will jump back a row. Can't get pass that jumping row unless I drag the scroll bar down. Tried reinstalling the app, but it didn't help.

**Comment by kurtextrem** [comment]
I actually had the same issue and tried to debug it - then I restarted Chrome and cleared the cache and it simply started working again. 

The problem here is -- the loading mechanism is provided by Instagram, not by me, I only change the visuals. So if something breaks in scrolling, I can't do too much. Although the "it's magically working again" makes me think it's a bug in their code and I have no idea why or what it could be.

**Comment by vwsvws** [comment]
Clearing cache and restart didn't work for me :(

I see, thanks! Hopefully they'll fix it soon then. Because I actually rely on using your extension over Instagram's native app.

**Comment by tayfunyasar** [comment]
I'm facing same issue. I also cant scroll down.

**Comment by kurtextrem** [comment]
If anyone has any idea about how to solve this issue, please let me know. I permanently have this issue now too and spent the last few hours to think about solutions (like increasing scroll height), but unsuccessfully.

The workaround is to use the scrollbar, or press your scroll wheel once and scroll "past" the point where it is stuck.

At 2 per row the issue seems to be gone, or way less frequent.

The issue seems to happen when you scroll too fast, or more specific, when you scroll before more posts have been added to the DOM (= before the scrollbar size shrinked and jumped up a bit).

**Comment by bluehairisnice** [comment]
I'm viewing two per row, and a couple of days ago I actually thought it was resolved. I was scrolling as per normal for about 30 min with no problems. Then once the problem kicked in again it was worse than ever. I'd pull the scroll bar past the stick point, but then it would happen again on the very next row. Just that bad for that day though.

I just tried using auto scroll to get past as suggested - it jumps back a few times, but then does move past. Though no matter how far past that problematic row I go with auto scroll, as soon as I touch another mouse button it jumps all the way back to the previous sticking point. 

It's sticking a normal amount right now (roughly every 4-6 rows) and does it even if I scroll very slowly. 

I wish I had something more than to report the wackiness I see. Sadly I have zero technical expertise in this area so no helpful suggestions. :(

**Comment by kurtextrem** [comment]
It could be that it has something to do with the height of the posts... let's see if I can solve it. Still open to suggestions though

@bluehairisnice Thank you anyway, every report with details is helpful! :)

**Comment by kurtextrem** [comment]
I got an idea:

Virtual clone as solution. Proposal:
The original feed (one post per row) will remain in the background. Instagram by default loads a few posts, so scrolling is smooth.
I'll clone those and put them into the list that is shown to the user.

Now, when the user scrolls the shown list (virtual clone), whenever the user scrolls down (a new row enters the viewport), in the original list I'll let the viewport scroll by 2-4 posts, so new posts get loaded too.

I think this could work and is the only viable solution, apart from programming a separate feed. I'll do the latter if the virtual clone doesn't work out somehow.

**Comment by kurtextrem** [comment]
The clone experiment failed, as I can't get a working scroll mechanism :(

This means I will have to implement my own Instagram feed with all the features:

- [ ] like a post
- [ ] save a post. Maybe I can even add collections in that case, saving to a specific collection on the web
- [ ] add comment 
- [ ] multiple media posts
- [ ] video start
- [ ] tagged users
- [ ] scrolling

and in general of course:
- [ ] the post itself + design

**Comment by kurtextrem** [comment]
This update will be rolled out in the next few days. Things I have yet to implement can be seen above.

**Comment by kurtextrem** [comment]
I have good and bad news:
The good news first: I've released an update on the Chrome web store, and the feed is perfectly working now!

The bad news: My extension needs permissions to communicate with the Instagram API (to get likes and collections), which require in-depth explanation to the Chrome Web Store Team (this has always been the case, but they made updating more strict to fight malware). This means it can take weeks until v3.0.0 is rolled out :|
