### ISSUE TITLE
New custom feed is above IG notifications/warnings

### ISSUE THREAD

**Issue by KLVN** [kurtextrem/Improved-for-Instagram#67]
Hi, first of all thank you for this big(ger) update :D

I just noticed this small bug, that the new custom feed is positioned at a fixed height and therefore is above Instagrams "COVID-19 notification".
![image](https://user-images.githubusercontent.com/8047980/78358735-f77d4800-75b3-11ea-9040-6c6377bb807a.png)

---

```
#ige_feed {
    top: 31vh;
}
```
This will push the feed downwards, revealing this notification, but also destroy everything else 😅
Closing this notification also doesn't help, because it will always show up again.

**Comment by kurtextrem** [comment]
Seems like IG is experimenting again, I don't have this notification.... I also don't have the direct messages (I think?) at the top

I guess hiding the notification is the option we should pick? Or maybe moving the feed down as with your code, and if the notification gets closed, save that it got closed, and put the feed to the normal position.

**Comment by KLVN** [comment]
DMs were introduced some weeks ago (in my case).

This notification is part of the 'old' feed. You can either hide the feed (`display: none`) or even delete the whole thing. Your extension will still work in both cases.

Here are the HTML and XPath representations:
```
<main class="SCxLW  o64aR " role="main">

//*[@id="react-root"]/section/main
```


(Btw, liking and un-liking are swapped. But looks like you already fixed it in 66b5ff1)

**Comment by kurtextrem** [comment]
The thing is, I hide the old feed, which is why this issue is quite confusing.

Does the HTML / XPath go deeper or is the IG notification the `<main>` element itself?

**Comment by KLVN** [comment]
This notification is "above" the hidden feed. Highlighted line is the notification; `<div style="flex-direction: column;...` is hidden by `content.css`:
![image](https://user-images.githubusercontent.com/8047980/78473076-05f76b00-773e-11ea-8217-2011cc893b90.png)

Here's the HTML of the notification (in case you're interested):
```
<div class="Igw0E     IwRSH      eGOV_         _4EzTm          qD5Mv">
    <section class="bR_3v  ">
        <div class="w03Xk">
            <button class="Ls00D coreSpriteDismissLarge Jx1OT"><span class="Szr5J">Schließen</span></button>
            <div class="pHxcJ"><img alt="" class="gAoda" src="https://scontent.fham3-1.fna.fbcdn.net/v/t39.3138-6/s110x80/89717785_525851141278293_1508545131723096064_n.png?_nc_cat=1&amp;_nc_sid=de96e1&amp;_nc_ohc=iC0zNi9_qdwAX_AciHn&amp;_nc_ad=z-m&amp;_nc_cid=0&amp;_nc_zor=9&amp;_nc_ht=scontent.fham3-1.fna&amp;oh=e7c573de1b16d06e1b7e0d5dd4c0f722&amp;oe=5EAFFBBD" decoding="async"><span class="_0DvBq"><div class="gAo1g">Hilf mit, die Ausbreitung des Coronavirus zu verhindern</div><div class="nwq6V">Hier findest du die aktuellsten Informationen des Bundesministeriums für Gesundheit, mit denen du dabei helfen kannst, die Ausbreitung von COVID-19 zu verhindern.</div></span><span class="DZiHE"><a href="https://www.bundesgesundheitsministerium.de/coronavirus.html" rel="nofollow noopener noreferrer" target="_blank"><div class="                   Igw0E     IwRSH      eGOV_         _4EzTm                                                          DhRcB                                                    "><button class="aPBwk  sqdOP  L3NKy _4pI4F  y3zKF     " type="button">Weiter zu bundesgesundheitsministerium.de</button></div></a></span></div>
        </div>
    </section>
</div>
```

And (full) XPath:
```
//*[@id="react-root"]/section/main/section/div[1]/div[1]
/html/body/div[1]/section/main/section/div[1]/div[1]
```

**Comment by kurtextrem** [comment]
What's your opinion, would you simply hide it or do you think that noficiation (or possibly others) are important?

**Comment by KLVN** [comment]
Well... it _could_ be something important ¯\\_(ツ)_/¯ But on the other hand this is the first time I've seen something like this and it's an absolutely exceptional case. On top of that it's only visible on the website, not in the app (or I dismissed it already and forgot about it), so it can't be _that_ important.
If you push down the custom feed by _x_ pixels, it may be possible that the next notification has a different height _y_, so you have to update the code for every new one, which is not the best solution.

Because dismissing this notification doesn't even work (it pops up every single time) and pushing down everything will also destroy everything, I would simply hide it :D

**Comment by kurtextrem** [comment]
Thanks, done!
