### ISSUE TITLE
Unable to type/click in the login page and in the settings options (gear icon)

### ISSUE THREAD

**Issue by Notare** [kurtextrem/Improved-for-Instagram#68]
After the last update, with the extension enabled I'm unable to type in the login page and get this layout:
https://i.imgur.com/qcHaWLF.jpg
I have to disable the extension to login and then enable it again.
Another issue is if I go to my profile and try to click in the gear icon (settings options), it doesn't happen anything.
Anyway, the posts per row function without the scrolling issues is spectacular, I'll try with more than 4.

**Comment by kurtextrem** [comment]
Thank you for the report, will fix as soon as possible!

**Comment by kurtextrem** [comment]
Regarding the gear icon: Issue is fixed in 3.0.1, waiting for Chrome Web Store approval.
