### ISSUE TITLE
Dots are blocking buttons

### ISSUE THREAD

**Issue by KLVN** [kurtextrem/Improved-for-Instagram#71]
Posts with multiple items have these indicator dots that are blocking the other elements. They are not clickable in the center.

![image](https://user-images.githubusercontent.com/8047980/80523972-31f9bb00-898f-11ea-8fa2-21531fb5a08c.png)

Note to myself: censor usernames with developer tools :D

**Comment by kurtextrem** [comment]
Ty, will go live with the next update
