### ISSUE TITLE
Stories tab not working [Bug]

### ISSUE THREAD

**Issue by PaoloC95** [kurtextrem/Improved-for-Instagram#72]
Stories tab show suggestions by instagram and the layer, between the rows post, of stories appear look like a new apart tab of the site.

**Comment by kurtextrem** [comment]
Yup, noticed it already.. they completely broke it again and restoring functionality is not too easy (while moving it to the right side like it used to). I'm working on a fix atm. 

What would you say, would it be okay to temporarily have the stories above the normal feed?

**Comment by PaoloC95** [comment]
yeah, sure, no problem, it was for notice them! :)
