### ISSUE TITLE
Italian Language added

### ISSUE THREAD

**Issue by PaoloC95** [kurtextrem/Improved-for-Instagram#73]
I've translate the file of langs to italan. 
It's attached here.
https://pastebin.com/AU8aVMMd

**Comment by kurtextrem** [comment]
Thank you so much!

**Comment by kurtextrem** [comment]
Sadly, I've stopped using translations for a while, as I had to do German and English on my own, so I've just put English in most places. I'll try to add more translation strings in the future.

**Comment by kurtextrem** [comment]
Will re-open when there are more strings to translate, thank you again!
