### ISSUE TITLE
background tabs have blurry images

### ISSUE THREAD

**Issue by ViperCode7** [kurtextrem/Improved-for-Instagram#77]
When loading (e.g. bookmarked / ) profiles in background tabs, the images listed in the profile are blurry, s150x150 in the source. If it loads in the foreground it loads properly.

As a side issue, the style modifications seem to also mess with page zooming... it's not a problem, though.

**Comment by kurtextrem** [comment]
That's a really weird issue, I'll see what I can do.

**Comment by kurtextrem** [comment]
Doesn't seem to happen for me, though. I might have an idea why it's happening, let's see.

**Comment by kurtextrem** [comment]
Should be fixed.
