### ISSUE TITLE
stuck on preloading, profile to home

### ISSUE THREAD

**Issue by ViperCode7** [kurtextrem/Improved-for-Instagram#80]
When viewing a profile, then clicking the instagram logo / home icon brings me to home page, where the 3 bouncing dots for preloading are being displayed endlessly. The left stories bar is populated properly, top to bottom. If I reload the page, the posts show again. I've disabled all other exts for this test.

Console.log:
Uncaught TypeError: Cannot read property 'watchPosts' of undefined
    at addWatched (main.js:388)
    at main.js:623
[stories Array(), Object... twice]
Uncaught TypeError: Cannot read property 'children' of null
    at MutationObserver.observe.childList (main.js:586)

**Comment by kurtextrem** [comment]
This is a quite complicated issue to solve, as simple as it sounds. Would be a page-reload fine if this happens?

**Comment by ViperCode7** [comment]
Well, since it started happening I've always loaded the main page in a new tab, instead of the current one. Which in essence worked around it.

**Comment by notNSANE** [comment]
any news about this? The extension is practically unusable.

**Comment by kurtextrem** [comment]
@notNSANE I think you're talking about a different issue. The problem is, the web store is slow in releasing updates, and I've fixed that issue already. It will be live on Monday I assume.
