### ISSUE TITLE
image resolution

### ISSUE THREAD

**Issue by ViperCode7** [kurtextrem/Improved-for-Instagram#81]
The image res now loads in 480x480 in listing and 640x640 in modal window instead of the highest available in srcset. So open image in new tab won't open the highest res possible.

**Comment by kurtextrem** [comment]
Any example? For me it works correctly.

**Comment by ViperCode7** [comment]
The issue happens **on profiles, not on the homepage of instagram**, there all are loading as 1080.

![1 inspect](https://user-images.githubusercontent.com/6399179/87303991-c5697380-c51c-11ea-8860-6d47803b781f.jpg)
![2 open in new tab](https://user-images.githubusercontent.com/6399179/87304000-c7333700-c51c-11ea-927d-90e0e1bfff95.jpg)

The src of the image in either the modal window or its own page is 1080w but if I open it in a new tab, using the right click context menu on the respective image, I'm getting the 640w version.

It happens on any profile, with or without other extensions present, in normal and incognito mode.
I've used https://www.instagram.com/therock/ and https://www.instagram.com/p/CCjDYEtFWAf/ respectively as examples.

If I remove the srcset attribute completely, it will use the src value, the 1080w one. But if I alter the URL just for the 640w in the set, it will show a broken image placeholder. So it uses by default the 640w address. Afterwards I also removed the 640w entry and it loaded the next one in the set, the 750w.

Played around with page zoom, and it changes the resolution of the loaded image. Zoomed to 110%, it used to load the 640w, now it loaded the 750w one, confirmed by opening it in new tab, in the same session without closing the modal window or changing to another image. Zoomed to 150%, it loaded the 1080w one. On some pictures 200% zoom with load the 1080w version.

I suspect different screen resolutions coupled with page zoom will trigger loading of a different image address from the srcset.
I have a 1080p monitor, and it doesn't go higher, and I use an 80% page zoom on instagram.

**Comment by kurtextrem** [comment]
Can you please check, using the devtools:
`navigator.connection.type` and `navigator.connection.downlink`?

**Comment by ViperCode7** [comment]
Well, these are all the navigator connection values:
type: undefined
downlink: 10
rtt: 50ms
downlinkMax: undefined
effectiveType: 4g
saveData: false

**Comment by kurtextrem** [comment]
Uh, seems like a Chrome update broke something then.
