### ISSUE TITLE
Support for carousel posts

### ISSUE THREAD

**Issue by kurtextrem** [kurtextrem/Improved-for-Instagram#9]

**Comment by badger200** [comment]
ARe "Carousel posts" the new multi-photo posts? Does IG have an API for 3rd parties to access those? I haven't seen a single iOS app (or any 3rd party app anywhere) that's been able to access the multi photos yet, so I'm curious.

**Comment by kurtextrem** [comment]
Yes, those are carousel posts. The API I'm using is not really a 3rd party API, it's the API their App is using as well. The carousel "data" is included in the JSON data they return, see: https://github.com/kurtextrem/Improved-for-Instagram/blob/master/src/components/post.js#L23 (temporarily I'm using the first image of the carousel until I fully support them)

**Comment by badger200** [comment]
@kurtextrem Oh that's briliant! I can't wait until 3rd party apps begin using the Carousel data, like IG image downloaders.

**Comment by kurtextrem** [comment]
done: https://github.com/kurtextrem/Improved-for-Instagram/commit/2be10229b3e32206a9ba0279bb36e05f98b05706
